#!/bin/bash

echo "Creating bucket ..."

name="yournamehere"

aws s3 mb s3://$name-09876

echo "Creating lifecycle config ..."

aws s3api put-bucket-lifecycle-configuration --bucket $name-09876 --lifecycle-configuration file://config.json

echo "Creating data2 folder and file.txt ..."

aws s3 cp file.txt s3://$name-09876/data2/file.txt

echo "Creating data1 folder ..."

aws s3api put-object --bucket $name-09876 --key data1

echo "Done!"